### ISSUE TITLE
Autopub fails

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/clipboard-apis#123]
@tabatkins, really sorry to bother you but could use a little BikeShed help... when we try to auto-publish this spec, Echidna fails because the "previous-version" doesn't match the previously published version. 

The only way we've managed to get it to work is to manually update "Previous Version:" in the .bs file (which is not amazing). Is there something we need to manually do avoid this problem? I tried deleting "Previous Version:" entirely, but that didn't help :(

**Comment by tabatkins** [comment]
Ah, `Previous Version` being manually maintainable (because you don't publish very often and there's a human in the loop) was an assumption of that design.

Hmm. Dated versions should show up in the bibliography data if you're publishing to /TR. I suppose I could have a value that would opt into auto-filling the URL from there. It wouldn't be correct if you hadn't updated your data recently, or if there was a delay in SpecRef, but those are relatively dependable, and you can always fill things in manually if they fall over.

Okay, yeah, I'll add a `Previous Version: from biblio BIBLIO-KEY` value (allowing you to omit the `BIBLIO-KEY` part if your versioned unversioned shortname is in the biblio data already). I think that would address this?

**Comment by marcoscaceres** [comment]
Yes, I think that would address it. Thanks for the confirming what was wrong. I'll update manually for now.

**Comment by tabatkins** [comment]
And done. Just use `Previous Version: from biblio` and it'll auto-populate that entry from your bibliography data.

**Comment by siusin** [comment]
cc @deniak @jennyliang220

**Comment by deniak** [comment]
@siusin I believe this should be fix with @tabatkins' update

**Comment by marcoscaceres** [comment]
Sent a PR https://github.com/w3c/clipboard-apis/pull/130! Thanks again @tabatkins!
