### ISSUE TITLE
Should `clipboard.writeText()` replace `\n` characters with `\r\n` on Windows?

### ISSUE THREAD

**Issue by mbrodesser** [w3c/clipboard-apis#168]
Currently, Chromium seems to do that. However, it's not specified. Firefox doesn't do that.

That discrepancy was reported recently at https://bugzilla.mozilla.org/show_bug.cgi?id=1753202.

CC @snianu @BoCupp-Microsoft

**Comment by snianu** [comment]
Ah, that is correct. We do replace `\n` with `\r\n` on Windows. It is also true while writing [HTML headers](https://source.chromium.org/chromium/chromium/src/+/main:ui/base/clipboard/clipboard_util_win.cc;drc=71a469ae7160a2edd94c9503cc8af18d4d2ccb00;l=856) during standard HTML format write operation on Windows. This is also the expected behavior on Windows so I'm going to add this to the spec in #158

**Comment by mbrodesser** [comment]
Makes sense. Thanks.

**Comment by snianu** [comment]
#158 has been merged. Thanks for the feedback!
