### ISSUE TITLE
How should focus be managed?

### ISSUE THREAD

**Issue by MichielBijl** [w3c/clipboard-apis#26]
It is important to inform developers on how to manage focus with the use of the clipboard events. For example, where should focus move after a cut or paste command?

Could we work on a section that details this?

(this is part of an accessibility review for the APA WG: https://www.w3.org/WAI/APA/track/)

**Comment by hallvors** [comment]
@MichielBijl thanks for your review and the issues. I've attempted to keep this spec focused on what happens between the browser engine and the JavaScript. Questions like how exactly pasted data is inserted into the DOM or how focus / cursor should be positioned after inserting various types of data seem off-topic.. Perhaps these questions indicate we need a more general "cutting and pasting" spec rather than a "Clipboard API" spec?

**Comment by MichielBijl** [comment]
We are discussing this next week on the APA call; I'll keep you posted.

**Comment by chaals** [comment]
@hallvors I appreciate the effort to keep the focus tight and clear.

There is a section in HTML on managing focus, which is somewhat patchy - but it might be the place to put in stuff about what happens after operations like cut/paste. This might also be something that should pass through the editing group, since I think focus is pretty important for them too.

I suspect we don't need to put it into the clipboard spec itself.

**Comment by MichielBijl** [comment]
@chaals is this the section you refer to: [HTML 5.1 Focus](https://w3c.github.io/html/editing.html#focus)?

**Comment by hallvors** [comment]
:+1: Focus handling is a big and important topic, it's good to see the HTML spec pay more attention to it. 

@MichielBijl May I close this issue and expect you to follow this up with the HTML and/or Selection folks? I have one requirement about focus (as far as I can remember) which is if JS during paste event processing moves focus, the pasting must target the control that *gained* focus. I think everything else about focus handling applies equally to editing in general ('cut' being like 'delete' focus-wise etc.) and thus nothing to add to my spec..

**Comment by MichielBijl** [comment]
@hallvors sounds good to me.

**Comment by annevk** [comment]
@hallvors I think it would be good to file an issue against https://github.com/whatwg/html/issues/new listing those requirements.

(We should probably also figure out the other dependencies between HTML and this specification, such as the Clipboard interface.)

**Comment by hallvors** [comment]
@annevk I'll leave that to @MichielBijl and his APA reviewers in the blissful belief that they will know more about these requirements than I do :)

**Comment by hallvors** [comment]
@annevk convinces me that I should add references to for example https://w3c.github.io/html/editing.html#focused and https://w3c.github.io/html/editing.html#focusable to define the concepts I'm using in my single focus-related requirement. I'll might as well reopen this bug and use it for that purpose..

**Comment by hallvors** [comment]
https://html.spec.whatwg.org/multipage/interaction.html#focused

**Comment by MichielBijl** [comment]
For what it's worth, if the APA decides the HTML spec focus management section needs clarification on this; I will take that on. @hallvors can I get you to review that if necessary? Would be great to have someone read changes that knows the Clipboard API.

**Comment by hallvors** [comment]
Sure

**Comment by MichielBijl** [comment]
We're [moving this into the HTML spec](https://github.com/w3c/html/issues/166), so this can be closed :)

**Comment by annevk** [comment]
Not really, the clipboard API will need updates for this.
