### ISSUE TITLE
Behavior of queryCommandEnabled

### ISSUE THREAD

**Issue by zetafunction** [w3c/clipboard-apis#7]
Right now, queryCommandEnabled("paste") in Chrome only returns true if we're in an editable area (and https://dvcs.w3.org/hg/editing/raw-file/tip/editing.html#enabled specifically mentions that cut and paste are not always enabled, though it doesn't really define when that would be).

However, executing a paste via the top-level menu or the key combination still fires a paste event at the page.

It seems like queryCommandEnabled("paste") should just match when we allow execCommand("paste") / Ctrl+V / etc?

**Comment by hallvors** [comment]
See #4 for an alternative suggestion.
We don't want to limit paste actions to only editable areas. If you write a file manager web app, it should support "cut" and "paste" of files without any hacks like placing  cursor in a hiddenish editable field..

**Comment by joone** [comment]
queryCommandEnable("copy") also works differently among browsers: Firefox always return true because the api is used to check if the browser enables the operation, but in the case of Chomium browser, queryCommandEnable('copy') is used for enable/disabling the menu item "copy".  So, it can be disabled if there is no range selection.

**Comment by garykac** [comment]
This issue was moved to w3c/editing#161
