### ISSUE TITLE
Clarify promise rejection value

### ISSUE THREAD

**Issue by LinusU** [w3c/clipboard-apis#76]
I'm a bit unsure of what to expect back from the async clipboard API when there is a failure. The [`explainer.adoc`](https://github.com/w3c/clipboard-apis/blob/master/explainer.adoc) here doesn't use the rejection value at all, and the spec simply says "reject |p|".

https://github.com/w3c/clipboard-apis/blob/2ac3c0b5894558a4b468be6f09feb588efff4077/index.bs#L676

Is the intention that the Promise should simply reject with the value `undefined` instead of an `Error` instance?

This is how we have interpreted it here: feross/clipboard-copy#24

I feel that this goes against best practices, and I think there is a ton of code in the wild that does something similar to:

```js
runAllMythings().catch((err) => {
  console.log(err.stack)
})
```

Wouldn't it be nice to reject with an error, maybe `reject(new Error('Persmission for writing to clipboard was not granted'))`?

**Comment by gked** [comment]
@LinusU clipboard API should probably be able to relay `PermissionState `value back to the developer. @garykac what do you think if we added new property to `DataTransfer `  interface? Something like` readonly attribute PermissionState state;` with some default value.

**Comment by garykac** [comment]
We should definutely return better DOMExceptions, but I don't think we want to touch DataTransfer.

E.g., the spec should be updated to read:

```
   1. If |r| is not granted, then reject |p| with a "NotAllowedError" DOMException.
```

While the spec currently uses a DataTransfer object for `read`/`write`, I believe that we'll need to change that to a more appropriate object because of recent issues that were raised. Specifically https://github.com/w3c/clipboard-apis/issues/41 and https://github.com/w3c/clipboard-apis/issues/44 and [this comment from the TAG review](https://github.com/w3ctag/design-reviews/issues/222#issuecomment-379437797).

**Comment by gked** [comment]
@garykac using DOMExceptions like `NotAllowedError` seems a bit ambiguous. But I guess for the lack of a better alternative,I think, this should work. I am checking Travis about why DataTransfer can't just do the job.

**Comment by garykac** [comment]
Re: "NotAllowedError", see the comments [here](https://heycam.github.io/webidl/#invalidaccesserror) for the recommendation to use this for denied requests.

Questions about the appropriateness of DataTransfer came about before the TAG review because it doesn't quite match what we'll need to do for the clipboard:
* Images can be on the clipboard multiple times (in different formats)
* We'll need placeholders for delay-generated data

We could hack these things on top of DataTransfer, but that's not necessarily the best approach.
